version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bill_bot
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/your-creds.json
      
    networks:
      - bill_network  # hoặc bill_network nếu bạn dùng tên đó

networks:
  bill_network:
    external: true